# Generated by Django 4.1.2 on 2022-11-08 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                ("_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "email",
                    models.EmailField(
                        max_length=255, unique=True, verbose_name="email"
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="username"
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "date_joined",
                    models.DateTimeField(auto_now_add=True, verbose_name="date-joined"),
                ),
                (
                    "last_login",
                    models.DateTimeField(auto_now=True, verbose_name="last-login"),
                ),
                ("is_admin", models.BooleanField(default=False)),
                ("is_staff", models.BooleanField(default=False)),
                ("is_superuser", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("is_teacher", models.BooleanField(default=True)),
                ("is_parent", models.BooleanField(default=False)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
